### ISSUE TITLE
challenge06 az login not working

### ISSUE THREAD

**Issue by kawsark** [CardinalNow/TerraformWorkshop#4]
Hello,
Thank you for publishing this valuable repository. I am getting the following error on Challenge 06 at the point where `module "windowsservers"` is being added when using Azure Cloud Shell. Despite doing subsequent `az login` the following error persists. I am able to workaround the problem by using a Service Principal instead.

I fount this GH issue and I think it was already fixed in the 1.13.0 Provider code:
[GH Issue 1395](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1395)

Is the module using a lower code version?
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.azurerm: Azure CLI Authorization Tokens were not found. Please ensure the Azure CLI is installed and then log-in with `az login`.
```

**Comment by straubt1** [comment]
If you remove the provider version check you should be good to go.
There is a slight refresh to this repo coming in the next few weeks as we prepare another round of workshops, this feedback will be incorporated into those changes.
Thanks for the Issue!

**Comment by straubt1** [comment]
Just went through the entire workshop for an upcoming delivery, minor changes have been made, and I was able to create all the infrastructure.
Hope this helps.
